#platform.team@lge.com	2011.01

obj-$(CONFIG_LGE_FELICA_DCM) += felica_pon.o felica_rfs.o felica.o felica_gpio.o felica_rws.o felica_uart.o felica_i2c.o felica_cen.o felica_cal.o felica_common.o felica_test.o
obj-$(CONFIG_LGE_FELICA_KDDI) += felica_pon.o felica_rfs.o felica.o felica_gpio.o felica_rws.o felica_uart.o felica_i2c.o felica_cen.o felica_cal.o felica_common.o felica_test.o


